# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 14:18
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20171124_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('heading', models.TextField(max_length=32)),
                ('text', models.TextField(max_length=256)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='static/media/blog/attachments/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='blogs',
            unique_together=set([('user', 'heading')]),
        ),
    ]
