# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171124_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='secret_word',
            field=models.TextField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
