# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171130_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='secret_word',
            field=models.CharField(max_length=32),
        ),
    ]
